version: '2.1'
services:
  redis:
    image: redis:3-alpine

  airflow-webserver:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/var/lib/airflow/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    env_file: .env
    external_links:
      - postgres:database.service.rasterfoundry.internal
    links:
      - redis:cache.service.rasterfoundry.internal
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_PARALLELISM=8
      - AIRFLOW_FERNET_KEY=secret
      - AIRFLOW_BASE_URL=http://localhost:8080
      - AIRFLOW_WEBSERVER_WORKERS=1
      - AIRFLOW_SECRET_KEY=secret
      - AIRFLOW_CELERY_CONCURRENCY=2
      - RF_HOST=http://rasterfoundry.com:9000
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-flower:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    external_links:
      - postgres:database.service.rasterfoundry.internal
    links:
      - redis:cache.service.rasterfoundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_REMOTE_LOG_FOLDER=
      - AIRFLOW_REMOTE_LOG_CONN_ID=
      - AIRFLOW_PARALLELISM=8
      - AIRFLOW_FERNET_KEY=secret
      - AIRFLOW_BASE_URL=http://localhost:8080
      - AIRFLOW_WEBSERVER_WORKERS=1
      - AIRFLOW_SECRET_KEY=secret
      - AIRFLOW_CELERY_CONCURRENCY=2
      - RF_HOST=http://rasterfoundry.com:9000
    ports:
      - "5555:5555"
    command: airflow flower

  airflow-scheduler:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/var/lib/airflow/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    restart: always
    external_links:
      - postgres:database.service.rasterfoundry.internal
    links:
      - redis:cache.service.rasterfoundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_REMOTE_LOG_FOLDER=
      - AIRFLOW_REMOTE_LOG_CONN_ID=
      - AIRFLOW_PARALLELISM=8
      - AIRFLOW_FERNET_KEY=secret
      - AIRFLOW_BASE_URL=http://localhost:8080
      - AIRFLOW_WEBSERVER_WORKERS=1
      - AIRFLOW_SECRET_KEY=secret
      - AIRFLOW_CELERY_CONCURRENCY=2
      - PYTHONPATH=/opt/raster-foundry/app-tasks/rf/src/
      - RF_HOST=http://rasterfoundry.com:9000
    command: airflow scheduler

  airflow-worker:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - ./app-backend/batch/target/scala-2.11/rf-batch.jar:/opt/raster-foundry/jars/rf-batch.jar
      - $HOME/.aws:/var/lib/airflow/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    external_links:
      - postgres:database.service.rasterfoundry.internal
      - api-server:rasterfoundry.com
    links:
      - redis:cache.service.rasterfoundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_REMOTE_LOG_FOLDER=
      - AIRFLOW_REMOTE_LOG_CONN_ID=
      - AIRFLOW_PARALLELISM=8
      - AIRFLOW_FERNET_KEY=secret
      - AIRFLOW_BASE_URL=http://localhost:8080
      - AIRFLOW_WEBSERVER_WORKERS=1
      - AIRFLOW_SECRET_KEY=secret
      - AIRFLOW_CELERY_CONCURRENCY=2
      - RF_HOST=http://rasterfoundry.com:9000
    command: airflow worker

  airflow-worker-spark:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/var/lib/airflow/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    external_links:
      - postgres:database.service.rasterfoundry.internal
      - api-server:rasterfoundry.com
    links:
      - redis:cache.service.rasterfoundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - AIRFLOW_REMOTE_LOG_FOLDER=
      - AIRFLOW_REMOTE_LOG_CONN_ID=
      - AIRFLOW_PARALLELISM=8
      - AIRFLOW_FERNET_KEY=secret
      - AIRFLOW_BASE_URL=http://localhost:8080
      - AIRFLOW_WEBSERVER_WORKERS=1
      - AIRFLOW_SECRET_KEY=secret
      - AIRFLOW_CELERY_CONCURRENCY=2
      - RF_HOST=http://rasterfoundry.com:9000
    command: airflow worker -q spark
