envdir_home: "/etc/rf.d/env"

envdir_config:
  RF_DB_NAME: "{{ postgresql_database }}"
  RF_DB_USER: "{{ postgresql_username }}"
  RF_DB_PASSWORD: "{{ postgresql_password }}"
  RF_DB_HOST: "{{ postgresql_host }}"
  RF_DB_PORT: "{{ postgresql_port }}"
  RF_STATSD_HOST: "{{ statsite_host }}"
  RF_CACHE_HOST: "{{ redis_host }}"
  RF_CACHE_PORT: "{{ redis_port }}"
  RF_AWS_SECRET: "{{ aws_secret }}"
  RF_AWS_KEY: "{{ aws_key }}"
  RF_AWS_BUCKET: "{{ aws_bucket }}"
