---
worker_home: /opt/worker
worker_deploy_branch: "master"

worker_config:
  DJANGO_TEST_DB_NAME: "{{ django_test_database }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
  DJANGO_POSTGIS_VERSION: "{{ worker_postgis_version }}"
  DJANGO_SECRET_KEY: "{{ app_secret_key }}"
  DJANGO_STATIC_ROOT: "{{ worker_static_root }}"
  DJANGO_MEDIA_ROOT: "{{ worker_media_root }}"

worker_postgis_version: 2.1.3
worker_secret_key: "{{ postgresql_password | md5 }}"

worker_log: /var/log/rf-worker.log
worker_log_rotate_count: 5
worker_log_rotate_interval: daily
worker_static_root: ""
worker_media_root: ""
