---
- hosts: app-servers
  sudo: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Add monitoring hostname to /etc/hosts
      lineinfile: dest="/etc/hosts"
                  regexp="^127.0.0.1"
                  line="127.0.0.1 localhost {{ statsite_host }}"
      when: "['packer'] | is_in(group_names)"

  roles:
    - { role: "raster-foundry.app" }
    - { role: "raster-foundry.mock-geoprocessing", when: "['development', 'test'] | some_are_in(group_names)" }

  post_tasks:
    - name: Revert change to /etc/hosts
      lineinfile: dest="/etc/hosts"
                  regexp="^127.0.0.1"
                  line="127.0.0.1 localhost"
      when: "['packer'] | is_in(group_names)"
