- src: azavea.docker
  version: 4.0.0

- src: azavea.pip
  version: 1.0.0

- src: azavea.jenkins
  version: 1.2.0

- src: azavea.nginx
  version: 0.3.0

- src: azavea.ntp
  version: 0.1.1

- src: azavea.packer
  version: 0.2.0
